# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ros_study/Sys.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Sys(genpy.Message):
  _md5sum = "6c474b8d8a1c88a0d03e2a77e0dd4bce"
  _type = "ros_study/Sys"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 cpu_percent
float32 virtual_memory_percent
uint64 disk_free
uint64 net_packets_recv
float32 coretemp"""
  __slots__ = ['cpu_percent','virtual_memory_percent','disk_free','net_packets_recv','coretemp']
  _slot_types = ['float32','float32','uint64','uint64','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       cpu_percent,virtual_memory_percent,disk_free,net_packets_recv,coretemp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Sys, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.cpu_percent is None:
        self.cpu_percent = 0.
      if self.virtual_memory_percent is None:
        self.virtual_memory_percent = 0.
      if self.disk_free is None:
        self.disk_free = 0
      if self.net_packets_recv is None:
        self.net_packets_recv = 0
      if self.coretemp is None:
        self.coretemp = 0.
    else:
      self.cpu_percent = 0.
      self.virtual_memory_percent = 0.
      self.disk_free = 0
      self.net_packets_recv = 0
      self.coretemp = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2f2Qf().pack(_x.cpu_percent, _x.virtual_memory_percent, _x.disk_free, _x.net_packets_recv, _x.coretemp))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 28
      (_x.cpu_percent, _x.virtual_memory_percent, _x.disk_free, _x.net_packets_recv, _x.coretemp,) = _get_struct_2f2Qf().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2f2Qf().pack(_x.cpu_percent, _x.virtual_memory_percent, _x.disk_free, _x.net_packets_recv, _x.coretemp))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 28
      (_x.cpu_percent, _x.virtual_memory_percent, _x.disk_free, _x.net_packets_recv, _x.coretemp,) = _get_struct_2f2Qf().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2f2Qf = None
def _get_struct_2f2Qf():
    global _struct_2f2Qf
    if _struct_2f2Qf is None:
        _struct_2f2Qf = struct.Struct("<2f2Qf")
    return _struct_2f2Qf
